"""empty message

Revision ID: 193f5a035540
Revises: e3c7efe5b33e
Create Date: 2019-10-18 19:49:11.509110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '193f5a035540'
down_revision = 'e3c7efe5b33e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grade', sa.Column('manage_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'grade_ibfk_1', 'grade', type_='foreignkey')
    op.create_foreign_key(None, 'grade', 'user', ['manage_id'], ['id'])
    op.drop_column('grade', 'manag_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grade', sa.Column('manag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'grade', type_='foreignkey')
    op.create_foreign_key(u'grade_ibfk_1', 'grade', 'user', ['manag_id'], ['id'])
    op.drop_column('grade', 'manage_id')
    # ### end Alembic commands ###
