"""empty message

Revision ID: 7cab72bf6b56
Revises: 193f5a035540
Create Date: 2019-10-18 19:59:13.062453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cab72bf6b56'
down_revision = '193f5a035540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'grade_ibfk_1', 'grade', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'grade_ibfk_1', 'grade', 'user', ['manage_id'], ['id'])
    # ### end Alembic commands ###
