"""empty message

Revision ID: 90d4efe95c9c
Revises: 7220a6338cca
Create Date: 2019-10-11 17:33:54.654435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90d4efe95c9c'
down_revision = '7220a6338cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'telephone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telephone', mysql.VARCHAR(length=11), nullable=False))
    # ### end Alembic commands ###
