"""empty message

Revision ID: 959d3d38df4e
Revises: 
Create Date: 2019-10-22 19:14:43.865840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '959d3d38df4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('present', sa.Column('present_type', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('present', 'present_type')
    # ### end Alembic commands ###
