"""empty message

Revision ID: b355e5639d27
Revises: 959d3d38df4e
Create Date: 2019-10-25 23:41:07.719150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b355e5639d27'
down_revision = '959d3d38df4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('issend', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'issend')
    # ### end Alembic commands ###
