"""empty message

Revision ID: e3c7efe5b33e
Revises: 90d4efe95c9c
Create Date: 2019-10-11 17:42:25.228775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3c7efe5b33e'
down_revision = '90d4efe95c9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stuid', sa.String(length=11), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'stuid')
    # ### end Alembic commands ###
